version: "3.8"

services:
  todoapp:
    image: "santosh3007/todo-app:1.2"
    container_name: todo_app_frontend
    ports:
      - "80:3000"

  db:
    image: "postgres:12.9-alpine"
    container_name: todo_app_api
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    image: "santosh3007/todo-app-api:1.2"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - "3001:3001"
    environment:
      - DATABASE_HOST=db
    depends_on:
      - "db"

volumes:
  postgres:
